version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.3

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar -Dsonar.projectKey=elsantner_canteenMgmtBackend

  build-and-deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Install Heroku shell
          command: sudo curl https://cli-assets.heroku.com/install.sh | sh
      - run:
          name: Login to Heroku container registry
          command: HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:login
      - run:
          name: Build and push container
          command: HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:push -a ${HEROKU_APP_NAME} web
      - run:
          name: Deploy container
          command: HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:release -a ${HEROKU_APP_NAME} web

workflows:
  main:
    jobs:
      - build-and-test:
          context: SonarCloud
      - build-and-deploy:
          context: Heroku-<< pipeline.git.branch >>
          requires:
            # Deploy after testing.
            - build-and-test
          filters:
            branches:
              only:
                - main
                - development
